### ISSUE TITLE
Nuevo issue

### ISSUE THREAD

**Issue by bgazzera** [Paginar/test-boards#3]

**Comment by bgazzera** [comment]
Hola soy yo

**Comment by mcarena** [comment]
Hola

**Comment by mcarena** [comment]
@bgazzera que tal

**Comment by lschlaen** [comment]
hola

**Comment by bgazzera** [comment]
![react strategy - page 11 2](https://user-images.githubusercontent.com/6751553/37156258-56ca708e-22c4-11e8-8716-22527fad0be0.png)
